### ISSUE TITLE
Comparing two genomes

### ISSUE THREAD

**Issue by ramesh8v** [flexidot-bio/flexidot#4]
Say, I have two genomes. One is complete (pseudomolecule level assembly) and the other one is not complete yet (few Mb sized scaffolds). My question is, it possible to plot these two genomes to study genome rearrangements? I'm confused with `-p` options.

**Comment by molbio-dresden** [comment]
Hello ramesh8v, <br/>

thank you for your interest. We did not design FlexiDot for whole genome comparisons, but for customizability and integration of additional information (shadings, annotations etc.). Therefore you will face rather long computation times with FlexiDot, if you input whole genomes. We tested with sequences up to 100 kb, which took reasonable time. <br/>
In order to get an overview of your genomes, we recommend to try some of the fast genome-scale dotplot tools such as dgenies or Gepard. If you have an idea which sequences you want to use, you can still give FlexiDot a shot, but be prepared to wait a while. Parameters recommended would be long wordsizes `-k`,  and all-against-all comparison `-p 2` or pairwise comparison `-p 1`. <br/>
* All-against-all: All individual fasta files are compared to each other and the output will be a matrix.
* Pairwise: Only two sequences are compared individually. If you want one comprehensive image, you have to concatenate your sequences.    

Pairwise is a bit faster than all-against-all, but you won't see your scaffold positions or shadings/annotations. <br/>
Let us know, how your efforts turned out.

**Comment by jiadong324** [comment]
@molbio-dresden 
For the pairwise mode, can I put the two sequence in two individual .fa file and do the comparison? Or I have to put these two sequence in a file?

**Comment by molbio-dresden** [comment]
Hello @jiadong324,  <br>
thank you for your question. For all plotting modes, you can use one or multiple fasta files as input with one of the following three commands:

```
# use individual fasta file (can contain multiple sequences)
python flexidot.py -i input.fas [optional arguments]

# use multiple fasta files
python flexidot.py -i input1.fas,input2.fas [optional arguments]

# use all fasta files in current directory
python flexidot.py -a [optional arguments]
```

If you use the pairwise mode and input more than two fasta sequences (regardless if as individual files or as multi-fasta file), all pairwise comparisons will be computed. The output will be a collage of pairwise comparisons (`-c y`) or written to individual files (`-c n`).
